<?php
/**
 * Script dependencies for this block's editor script.
 *
 * Normally generated by @wordpress/scripts. The theme's blocks are plain
 * browser JS against the wp.* globals, so this file is maintained by hand and
 * the theme needs no JavaScript build step.
 *
 * @package Probo_Connect
 */

return array(
	'dependencies' => array(
		'wp-blocks',
		'wp-element',
		'wp-block-editor',
		'wp-components',
		'wp-i18n',
		'wp-server-side-render',
		'pp-block-repeater',
	),
	'version'      => '1.0.0',
);
